### ISSUE TITLE
Dependency details

### ISSUE THREAD

**Issue by joreilly** [piepacker/JamPadCompose#1]
How is this added as a dependency.....has it been published anywhere yet?

**Comment by Swordfish90** [comment]
Hi @joreilly . There are no available artifacts yet.

It's on my TODO list for the next few days. I'll ping you as soon as they are.

**Comment by Swordfish90** [comment]
Ok @joreilly artefacts are finally available on maven central:

https://central.sonatype.com/artifact/io.github.piepacker/jampadcompose

Hope you enjoy it. Feel free to reach out if you have any issue or feedback.
